yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.about, name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/ <int:post_id>/ ', views.post_detail, name='post_detail'),
    path("create/", views.post_create, name='post_create'),
    path("group", views.creat_group, name='group_cr'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('posts/<int:post_id>/delet/', views.delet_post, name='del'),
    path('like/<int:post_id>/', views.like, name='like'),
    path('likeping/<int:post_id>/', views.ping_like, name='like_ping'),
    
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'
handler400 = 'core.views.bad_request'
handler403crf = 'core.views.csrf_failure'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    
    

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
# Create your models here.
User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(
        unique=True,
        max_length=200,
        verbose_name='URL группы'
    )
    description = models.TextField(verbose_name='Описание')

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='groups',
        null=True,
        blank=True,
        verbose_name='Группа',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    count_likes = models.PositiveIntegerField(null=True)

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(verbose_name='Текст комента')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата комментария'
    )

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )


class Like(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post, Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ['title', 'slug', 'description']


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["text", "group", 'image']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .models import Follow, Post, Group, Comment, User, Like
from .forms import GroupForm, PostForm, CommentForm
from rest_framework.decorators import api_view
from rest_framework.response import Response

def user_in_group(user):
    return user.groups.filter(name='all').exists()


def index(request):
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)

@api_view(['GET'])
def ping_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    
    like = Like.objects.filter(post=post, user=request.user)
    print(like)
    if like.exists():
        return Response({'message': True})
    else:
        return Response({'message': False})



@login_required
def like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    like = Like.objects.filter(post=post, user=request.user)
    if like.exists():
        post.count_likes -= 1
        post.save()
        like.delete()
    else:
        post.count_likes += 1
        post.save()
        Like.objects.create(post=post, user=request.user)

    return redirect('posts:index')


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)

    post_list = group.groups.all().order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('group').order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    total = page_obj.paginator.count
    if Follow.objects.filter(author=author.id).exists():
        following = True
    else:
        following = False
    context = {
        "page_obj": page_obj,
        "author": author,
        "total": total,
        "following": following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    total = post.author.posts.count()
    form = CommentForm(request.POST or None)
    comments = Comment.objects.select_related('post').filter(post=post_id)
    context = {
        "post": post,
        "total": total,
        "form": form,
        "comments": comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def creat_group(request):
    form = GroupForm()
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    context = {
        'form': form,
    }
    return render(request, 'posts/group.html', context)


@login_required
def delet_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    name = Post.objects.filter(pk=post_id)
    name.delete()
    return redirect('posts:profile', post.author)

@login_required
# @user_passes_test(user_in_group)
def post_create(request):
    template = "posts/create_post.html"
    is_edit = False
    if request.method == "GET":
        context = {"form": PostForm(), "is_edit": is_edit}
        return render(request, template, context)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.count_likes = 0
        post.save()
        return redirect("posts:profile", request.user)
    context = {"form": form, "is_edit": is_edit}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post_s = get_object_or_404(Post, pk=post_id)
    is_edit = True
    if request.user != post_s.author:
        return redirect("posts:profile", post_s.author)
    if request.method == 'POST':
        form = PostForm(
            request.POST or None,
            instance=post_s,
            files=request.FILES or None
        )
        if form.is_valid():
            form.save()
            return redirect("posts:post_detail", post_id)
        return render(request, 'posts/create_post.html',
                      {'form': form,
                       "is_edit": is_edit})
    form = PostForm(instance=post_s)
    context = {
        'form': form,
        "is_edit": is_edit,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.select_related('author', 'group').filter(
        author__following__user=request.user
    )
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/follow.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect("posts:profile", username=author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
  {% block title %}
    {%if is_edit%}
    Редактировать пост
    {%else%}
    Новый пост
    {%endif%}
  {% endblock %}
  {% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {%if is_edit%}
            Редактировать пост
            {%else%}
            Новый пост
            {%endif%}
          </div>
          <div class="card-body">
            {% load user_filters %}

            {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
            {% endif %}

            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:"form-control"   }}
                {% if field.help_text %}
                  <small
                    id="{{ field.id_for_label }}-help"
                    class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %} 
              </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                  Сохранить
                  {% else %}
                  Добавить
                  {%  endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Подписки{% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    <h3>Подписки:</h3>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
      </li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=false as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    <br>
      {% if post.group.slug %}
       Все записи группы <a href="{% url 'posts:group_list' post.group.slug %}"> {{ post.group.title }}</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group.html
{% extends "base.html" %}
  {% block title %}
   Новая группа
  {% endblock %}
  {% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Новая группа
          </div>
          <div class="card-body">
            {% load user_filters %}

            {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
            {% endif %}

            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:"form-control"   }}
                {% if field.help_text %}
                  <small
                    id="{{ field.id_for_label }}-help"
                    class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %} 
              </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  Сохранить
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% load thumbnail %}
{% block content %}  
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>
    {{ group.description }}
  </p>
  {% for post in page_obj %}
   <article>
      <ul>
        <li>
          Группа: {{ post.group }}
        </li>
        <li>
         Автор: {{ post.author.get_full_name }} 
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "800x200" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      <p>{{ post.text }}</p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock  %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock title %}
{% cache 20 index_page %}
{% block content %}
      {% include 'posts/includes/switcher.html' %}
      <div class="container py-5">     
        <h1>Последние обновления на сайте</h1>
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.username }} <a href="{% url "posts:profile" post.author %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
                {{post.date}}
              </li>
            </ul>    
            <p>{{ post.text }}</p>
            {% if post.image%}
            <img src="media/{{post.image}}" class="card-img-top"  style="width: 18rem;">
          {%else%}
          <img src="media/posts/default.png" class="card-img-top"  style="width: 18rem;">

          {%endif%}
            {% if post.group %}
              <a href={% url 'posts:group_list' post.group.slug %}>все записи группы</a>
            {% endif %}
          </article>
          {% if user.is_authenticated %}
          <div class="likes">
            <span  class="like-icon" post_id="{{post.id}}" name="likeButton">♡</span>
            <br>
            <p  name="count">{{ post.count_likes }}</p>

          </div>
          {% endif %}
            <!-- Поля формы -->
         
        {% if not forloop.last %}<hr>{% endif %}

        {% endfor %}
        {% include 'includes/paginator.html' %}
        
      </div>  
      <script>
         const likeButtons = document.getElementsByName('likeButton');
        const countDisplays = document.getElementsByName('count');
        for (let i = 0; i < likeButtons.length; i++) {
          const url = `/likeping/${likeButtons[i].getAttribute("post_id")}/`; 
          
          fetch(url, {
                method: 'GET',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
            .then((response) => response.json())
            .then((data) => {
              if (data['message'] == true) {
                likeButtons[i].classList.toggle('liked');
              };
            })
            .catch((error) => {
                console.error('Error:', error);
                
            });
            
        
    }
    for (let i = 0; i < likeButtons.length; i++) {
        likeButtons[i].addEventListener('click', function() {
            // Toggle the "liked" state of the button
            this.classList.toggle('liked'); // Используем "this" для текущего элемента нажатия
            
            // Determine if we are adding or removing a like
            const isLiked = this.classList.contains('liked');
            const url = `/like/${likeButtons[i].getAttribute("post_id")}/`; // Обратите внимание, что {{ post.id }} должен быть доступен для каждой "лайк-кнопки"

            // Update the count displayed based on like/unlike action
            let currentCount = parseInt(countDisplays[i].textContent); // Используем индекс для соответствующего count
            countDisplays[i].textContent = isLiked ? currentCount + 1 : currentCount - 1;

            // Send a request to update like status on the server
            fetch(url, {
                method: 'GET',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
            .catch((error) => {
                console.error('Error:', error);
                // Revert the count in case of an error
                countDisplays[i].textContent = isLiked ? currentCount - 1 : currentCount + 1; 
                this.classList.toggle('liked'); // Revert the "liked" state
            });
        });
    }
  
   </script>
{% endblock  %}
{% endcache %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}Пост {{ post.text|slice:":30" }}{% endblock title %}
{% block content %}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li> 
            {% if post.group %}
               Группа: {{post.group}}
              <a href={% url 'posts:group_list' post.group.slug %}>все записи группы</a>
            {% endif %}  
            
            <li class="list-group-item">
              Автор: {{post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ total }}</span>
            </li>
            
            <a href={% url "posts:profile" post.author.username %}>все посты пользователя</a> 
            
          </ul>
        </aside>
       
        <article class="col-12 col-md-9">
          <p>
            {% thumbnail post.image "800x200" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            {{post.text}}
          </p>
          {%if post.author == request.user%}
          <a class="btn btn-primary" href={% url 'posts:post_edit' post.id %} >
            редактировать запись
          </a> 
          <a class="btn btn-primary" href={%url 'posts:del' post.id%}>
            Удалить запись
          </a>   
          {% endif %}
        {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
        
      {% endfor %} 
        </article>       
      </div> 
    </main>
{%endblock%}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{author.get_full_name }}{% endblock title %}
{% block content %}
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ total }} </h3> 
        {% if following %}
              <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button">
        Подписаться
      </a>
   {% endif %}
        <br></br>
        {% for post in page_obj %}  
        <article>
          <ul>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
          </ul>
          <p>
            {% thumbnail post.image "800x200" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
          {{post.text}}
          </p>
          
          <a href={% url "posts:post_detail" post.id %}>подробная информация </a>
          
          
        </article>     
        {% if post.group %}  
        <a href={% url 'posts:group_list' post.group.slug %}>все записи группы</a> 
      
        {% endif %}     
        <hr>
        {% endfor %}

        
        {% include 'includes/paginator.html'%}
      </div>
    </main>
    
{% endblock  %}